from __future__ import annotations

import argparse
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path


def parse_header_files(index_xml: Path) -> list[str]:
    root = ET.parse(index_xml).getroot()
    headers: list[str] = []

    for compound in root.findall("compound"):
        if compound.attrib.get("kind") != "file":
            continue
        name = (compound.findtext("name") or "").strip()
        if name.endswith(".h"):
            headers.append(name)

    headers.sort()
    return headers


def page_slug(header: str) -> str:
    return Path(header).stem


def render_header_page(header: str, project: str) -> str:
    # Remove .h from the header, replace _ with whitespace and capitalize
    title = header.replace(".h", "").replace("_", " ").title()
    underline = "=" * len(title)
    return "\n".join(
        [
            title,
            underline,
            "",
            ".. This file is auto-generated by scripts/generate_api_rst.py.",
            "",
            f".. doxygenfile:: {header}",
            f"   :project: {project}",
            "",
        ]
    )


def render_api_index(headers: list[str]) -> str:
    lines = [
        "API Reference",
        "=============",
        "",
        ".. This file is auto-generated by scripts/generate_api_rst.py.",
        ".. Do not edit manually; it is regenerated by `make docs`.",
        "",
        "``HTTPServer`` API documentation.",
        "",
        "Project Structure",
        "-----------------",
        "",
        "The project is organized into several key directories:",
        "",
        "* ``lib/``: Core library source code.",
        "    * ``lib/include/httpserver/``: Public header files defining the API.",
        "    * ``lib/src/``: Implementation files for the library logic.",
        "* ``src/``: Entry point for the example HTTP server application.",
        "* ``public/``: Directory containing static assets (HTML, CSS, JS) used by the example server.",
        "* ``tests/``: Suite of unit tests (GoogleTest) and integration tests (Pytest).",
        "",
        "Key Components",
        "--------------",
        "",
        "The following components form the core of the ``HTTPServer`` library:",
        "",
        "* **Server** (``server.h``): Manages the server lifecycle, socket listening, and connection dispatching.",
        "* **Router** (``router.h``): Maps incoming request paths and methods to application-defined handler functions.",
        "* **HTTP Parser** (``http_parser.h``): Parses raw network bytes into structured ``HttpRequest`` objects.",
        "* **HTTP Objects** (``http_object.h``): Defines the fundamental ``HttpRequest`` and ``HttpResponse`` data structures.",
        "* **Response Builder** (``http_response_builder.h``): A fluent helper for constructing HTTP responses.",
        "* **Thread Pool** (``thread_pool.h``): Manages a pool of worker threads for handling concurrent requests.",
        "* **Configuration** (``config.h``): Handles runtime server settings, including port, TLS, and performance limits.",
        "* **Connection Guard** (``connection_guard.h``): An RAII utility for managing and tracking active client connections.",
        "* **Periodic Cleanup** (``periodic_idle_ip_cleanup.h``): A background service for cleaning up inactive client IP records.",
        "* **Port** (``port.h``): A type-safe abstraction for handling network port numbers and representations.",
        "* **Logger** (``logger.h``): Provides thread-safe logging for server events and errors.",
        "* **Log Event** (``log_event.h``): Represents structured log data with key-value pairs.",
        "* **Log Level** (``log_level.h``): Defines severity levels (INFO, WARN, ERROR) for the logging system.",
        "* **Utilities** (``utils.h``): Shared helper functions for URI decoding, MIME-type lookup, and more.",
        "* **Metrics** (``metrics.h``): Tracks server-level performance data including active connections, request counts, response statuses, and latency.",
        "* **Umbrella Header** (``httpserver.h``): A single header including most common library components.",
        "",
        "Detailed API",
        "------------",
        "",
        ".. toctree::",
        "   :maxdepth: 1",
        "",
    ]
    lines.extend([f"   api/{page_slug(header)}" for header in headers])
    lines.append("")
    return "\n".join(lines)


def render_index_page() -> str:
    return """
HTTPServer Documentation
========================

.. This file is auto-generated by scripts/generate_api_rst.py.

A small, single-binary HTTP server library and example application written in modern C++.
It provides a minimal HTTP request parser, routing, static-file handling, and helpers for building
both HTTP and HTTPS servers.

This documentation site is generated with Sphinx + Breathe using Doxygen XML output for the C++ API.

Quick Start
-----------

This project uses CMake and provides a ``Makefile`` for common developer tasks:

.. code-block:: bash

   make build            # configure and build in ./build
   make run              # build then run the example server
   make test             # build and run all tests
   make clean            # remove build directory
   make format           # format the source code
   make docs             # build the documentation

Further Reading
---------------

* :doc:`installation` - How to install the library to your system.
* :doc:`usage` - Learn how to build applications using the library.
* :doc:`configuration` - Detailed reference for server settings.
* :doc:`architecture` - Deep dive into the server's internal design.
* :doc:`metrics` - Monitor server performance and usage.
* :doc:`testing` - Information about the project's testing strategy.

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   api
   usage
   configuration
   architecture
   metrics
   testing
   installation
"""


def render_installation_page() -> str:
    return """
Installation
============

.. This file is auto-generated by scripts/generate_api_rst.py.

This guide explains how to build and install the ``HTTPServer`` library on your system so you can use it in other projects.

Installation Script
-------------------

The project provides a dedicated script to handle the build and installation process: ``scripts/install_library.sh``.

How to Use
~~~~~~~~~~

To install the library to the default location (usually ``/usr/local``), run:

.. code-block:: bash

   ./scripts/install_library.sh

Custom Installation Prefix
~~~~~~~~~~~~~~~~~~~~~~~~~~

If you wish to install the library to a specific directory, you can pass the path as an argument to the script:

.. code-block:: bash

   ./scripts/install_library.sh /path/to/custom/location

What the Script Does
~~~~~~~~~~~~~~~~~~~~

1.  **Build Configuration**: It creates a clean build directory (``build_install``) and configures the project using CMake in ``Release`` mode.
2.  **Optimized Build**: It disables the build of tests and the example application (``BUILD_TESTING=OFF`` and ``BUILD_SERVER_APP=OFF``) to ensure a fast, library-only installation.
3.  **Cross-platform Support**: It automatically detects the number of CPU cores to perform a parallel build.
4.  **Sudo Handling**: If the installation prefix is not writable by the current user, it will automatically prompt for ``sudo`` to perform the installation.

Using the Installed Library
---------------------------

Once installed, you can use the library in your own C++ projects.

CMake Integration
~~~~~~~~~~~~~~~~~

The library exports its targets, allowing you to use ``find_package()`` in your ``CMakeLists.txt``:

.. code-block:: cmake

   find_package(HttpServer REQUIRED)

   add_executable(my_app main.cpp)
   target_link_libraries(my_app PRIVATE HttpServer::httpserver_lib)

Including Headers
~~~~~~~~~~~~~~~~~

You can then include any of the library's headers in your source code:

.. code-block:: cpp

   #include <httpserver/core/server.h>
   #include <httpserver/http/http_parser.h>

   // ... your code ...
"""


def render_usage_page() -> str:
    return """
Usage Guide
===========

.. This file is auto-generated by scripts/generate_api_rst.py.

This guide provides examples of how to use the ``HTTPServer`` library to build a web server.

Basic Server Setup
------------------

To start a server, you need to initialize the ``Server`` object (optionally with a configuration file), register your routes, and call ``start()``.

.. code-block:: cpp

   #include <httpserver/httpserver.h>

   int main() {
       using namespace HTTPServer;

       // Initialize server with a config file
       Server server("config.toml");

       // Safe shutdown on SIGINT/SIGTERM
       server.installSignalHandlers();

       // Define routes...

       // Start the blocking event loop
       server.start();
   }

Routing
-------

The ``Router`` is a singleton used to map HTTP methods and paths to callback functions.

Static Routes
~~~~~~~~~~~~~

Simple path matching for specific methods:

.. code-block:: cpp

   Router::instance().addRoute("GET", "/hello", [](const HttpRequest& req) {
       return Responses::ok(req, "Hello, World!");
   });

Dynamic Routes
~~~~~~~~~~~~~~

Paths can contain placeholders in the format ``{name}``. These are extracted and passed in the ``req.params`` map. You can use multiple placeholders in a single path.

.. code-block:: cpp

   Router::instance().addRoute("GET", "/post/{year}/{slug}", [](const HttpRequest& req) {
       auto year = req.params.at("year");
       auto slug = req.params.at("slug");
       return Responses::ok(req, "Viewing post from " + year + ": " + slug);
   });

Query Parameters
~~~~~~~~~~~~~~~~

The server also parses query parameters from the URL (e.g., ``?key=value``) and merges them into the same ``req.params`` map used for dynamic path variables.

.. code-block:: cpp

   // Handling a request like GET /search?q=cpp
   Router::instance().addRoute("GET", "/search", [](const HttpRequest& req) {
       auto it = req.params.find("q");
       if (it != req.params.end()) {
           return Responses::ok(req, "Search results for: " + it->second);
       }
       return Responses::badRequest(StatusCode::BadRequest);
   });

Route Precedence
~~~~~~~~~~~~~~~~

When multiple routes could potentially match a single request, the ``Router`` follows these precedence rules:

1. **Exact Matches**: Static routes take the highest priority.
2. **Dynamic Routes**: If no exact match is found, the server looks for dynamic routes with placeholders.
3. **Wildcard/Directory Routes**: If neither of the above match, the server attempts to match static directory routes.

For directory routes, the **longest prefix match** always wins. If you have both ``/static/`` and ``/static/images/`` registered, a request to ``/static/images/logo.png`` will be served from the more specific ``/static/images/`` handler.

Security & Sanitization
-----------------------

The router includes built-in protection against **Directory Traversal** attacks. Any attempt to use ``..`` in a URI to access files outside of a registered static directory (e.g., ``/static/../../etc/passwd``) will be blocked and return a ``401 Unauthorized`` response.

Serving Static Files
--------------------

You can serve an entire directory of static assets (HTML, CSS, JS) using a single route.

.. code-block:: cpp

   // Map /static/* to the local public/ directory
   Router::instance().addStaticDirectoryRoute("/static", "public/");

   // Or serve a specific file for a route
   Router::instance().addRoute("GET", "/", [](const HttpRequest& req) {
       return Responses::file(req, "public/index.html");
   });

Pre-made Responses
------------------

The ``Responses`` namespace provides high-level helpers for common response types.

*   **Responses::ok(req, body, [mime_type])**: Returns a 200 OK response with the given body. Defaults to ``text/plain``.
*   **Responses::file(req, path)**: Reads a file from disk and serves it with the correct ``Content-Type`` based on its extension.
*   **Responses::notFound(req)**: Returns a 404 response with a standard HTML error page.
*   **Responses::badRequest(status_code)**: Returns a response with the specified error code (e.g., 400, 403) and a standard HTML error page.
*   **Responses::redirection(req, port)**: Returns a 301 Moved Permanently response redirecting to the HTTPS version of the current path.

Response Building
-----------------

For more control, use the ``HttpResponseBuilder`` fluent API.

.. code-block:: cpp

   Router::instance().addRoute("POST", "/data", [](const HttpRequest& req) {
       return HttpResponseBuilder()
           .setStatus(StatusCode::CREATED)
           .setBody("{\\"status\\":\\"success\\"}")
           .setHeader("Content-Type", "application/json")
           .build(req);
   });

Logging
-------

The library includes a thread-safe singleton ``Logger`` and a ``LogEvent`` helper for structured logging.

Simple Logging
~~~~~~~~~~~~~~

Use the convenience macros for basic messages:

.. code-block:: cpp

   LOG_INFO("Server starting...");
   LOG_WARN("Rate limit exceeded for IP: " + ip);
   LOG_ERROR("Failed to open configuration file");

Structured Logging
~~~~~~~~~~~~~~~~~~

The ``LogEvent`` class allows you to build structured log lines with key-value pairs, which are easier to parse with log aggregators.

.. code-block:: cpp

   #include <httpserver/log_event.h>

   LOG_EVENT(LogLevel::INFO, 
       LogEvent("request_processed")
           .add("method", req.method)
           .add("path", req.path)
           .add("status", 200)
           .add("duration_ms", 5)
   );
"""


def render_metrics_page() -> str:
    return """
Metrics Monitoring
==================

.. This file is auto-generated by scripts/generate_api_rst.py.

The ``HTTPServer`` library includes a built-in metrics monitoring system to track server performance, load, and health.

Metrics Collection
------------------

The ``Metrics`` class is a thread-safe singleton that uses atomic counters to aggregate data across all worker threads without significant performance overhead.

Key Metrics Tracked
~~~~~~~~~~~~~~~~~~~

*   **Active Connections**: The current number of clients connected to the server.
*   **Total Requests**: The cumulative number of successfully parsed HTTP requests handled since startup.
*   **Response Status Groups**:

    -   **2xx**: Successful responses.
    -   **3xx**: Redirections (e.g., HTTP to HTTPS).
    -   **4xx**: Client errors (e.g., Not Found, Bad Request).
    -   **5xx**: Server errors.

*   **Total Bytes Transit**:

    -   **Bytes Received**: Total raw bytes read from client sockets.
    -   **Bytes Sent**: Total raw bytes written to client sockets.

*   **Request Processing Time**: Cumulative time (in milliseconds) spent processing requests from the first byte received to the response being sent.

Integration Points
------------------

Metrics are automatically collected at key stages of the request lifecycle:

1.  **Connection Tracking**: The ``ConnectionGuard`` increments the active connection count on entry and decrements it on destruction (RAII).
2.  **I/O Tracking**: The ``Server`` records byte counts every time data is successfully read from or written to a socket.
3.  **Request Tracking**: Total request count is incremented after a handler finishes processing.
4.  **Latency Tracking**: The server measures the wall-clock time from the start of request receipt to the completion of the response send.

Accessing Metrics
-----------------

You can access a point-in-time snapshot of the current metrics using the ``snapshot()`` method.

.. code-block:: cpp

   #include <httpserver/metrics.h>

   void logServerStats() {
       auto stats = Metrics::instance().snapshot();
       
       std::cout << "Active Connections: " << stats.d_activeConnections << "\\n";
       std::cout << "Total Requests: " << stats.d_totalRequests << "\\n";
       std::cout << "Total Received: " << stats.d_totalBytesReceived << " bytes\\n";
       
       if (stats.d_totalRequests > 0) {
           double avg_latency = static_cast<double>(stats.d_totalRequestProcessingTimeMs) / stats.d_totalRequests;
           std::cout << "Avg Latency: " << avg_latency << " ms\\n";
       }
   }
"""


def render_architecture_page() -> str:
    return """
Architecture
============

.. This file is auto-generated by scripts/generate_api_rst.py.

This page describes the internal design and concurrency model of the ``HTTPServer`` library.

Request Lifecycle
-----------------

When a client connects to the server, the request traverses through several components:

1. **Acceptance**: The ``Server`` loop accepts the new socket connection.
2. **Concurrency**: The connection is wrapped in a ``ConnectionGuard`` (for rate limiting) and enqueued in the ``ThreadPool``.
3. **Parsing**: A worker thread picks up the task and uses the ``HttpParser`` to translate the raw bytes into an ``HttpRequest`` object.
4. **Routing**: The ``Router`` matches the request method and path against registered routes.
5. **Handling**: The matching callback (handler) is executed, returning an ``HttpResponse``.
6. **Transmission**: The response is serialized and sent back over the socket.
7. **Cleanup**: RAII guards ensure resources (sockets, connection counts) are released even if an error occurs.

Concurrency Model
-----------------

The server uses a **Fixed Thread Pool** architecture to handle multiple concurrent requests efficiently without the overhead of creating new threads for every connection.

* **ThreadPool**: Manages a set of worker threads and a task queue. If the queue is full (defined by ``max_queue_size`` in config), new connections are rejected to prevent memory exhaustion.
* **ConnectionGuard**: Tracks the number of active connections per IP address. It uses a ``ConnectedIp`` map to enforce ``max_connections_per_ip`` limits.

Internal Safety Mechanisms
--------------------------

Idle IP Cleanup
~~~~~~~~~~~~~~~

To prevent the connection tracking map from growing indefinitely, the ``PerioidIdleIpCleanup`` component runs a background thread that periodically purges records for IPs that haven't connected within the ``idle_timeout_seconds`` window.

Signal Handling
~~~~~~~~~~~~~~~

The ``Server::installSignalHandlers()`` method sets up listeners for ``SIGINT`` and ``SIGTERM``. When received, the server initiates a graceful shutdown, allowing active requests to finish before stopping the worker threads and closing listeners.
"""


def render_config_page() -> str:
    return """
Configuration Reference
=======================

.. This file is auto-generated by scripts/generate_api_rst.py.

The server can be configured using a TOML file passed to the ``Server`` constructor.

Section: [ports]
----------------

* ``server_port``: The primary port the server listens on (default: 443).
* ``http_redirection_port``: The port used for plain HTTP traffic if redirection is enabled (default: 80).

Section: [https]
----------------

* ``enable_https``: Boolean to enable/disable TLS (requires certificates).
* ``cert_file``: Path to the PEM-encoded SSL certificate.
* ``key_file``: Path to the PEM-encoded private key.
* ``enable_http_redirection``: If true, traffic on the HTTP port is redirected to HTTPS.

Section: [idle-ip-cleanup]
--------------------------

* ``interval_seconds``: Time in seconds between background cleanup tasks (default: 600).
* ``idle_timeout_seconds``: How long a client IP must be inactive before its records are removed (default: 300).

Section: [network]
------------------

* ``client_timeout_seconds``: Socket read timeout for client connections (default: 5).
* ``default_http_redirection_port``: The fallback port used for redirects if not otherwise specified.
* ``recv_buffer_size``: The size in bytes for the socket receive buffer (default: 4096).

Section: [threading]
--------------------

* ``min_threads``: Minimum number of worker threads in the pool (default: 4).
* ``max_threads``: Maximum number of worker threads in the pool (default: 32).
* ``max_queue_size``: Maximum number of pending tasks before rejecting new connections (default: 1024).

Section: [rate-limits]
----------------------

* ``max_connections_per_ip``: Maximum concurrent connections allowed from a single client IP (default: 10).
* ``max_keep_alive_requests``: Maximum requests allowed per persistent connection (default: 100).
* ``max_tokens`` / ``refill_rate``: Parameters for the token-bucket algorithm used for rate limiting.

Section: [http-config]
----------------------

* ``max_header_bytes``: Maximum allowed size for HTTP headers (default: 16KB).
* ``max_body_bytes``: Maximum allowed size for the HTTP request body (default: 10MB).
* ``allowed_methods``: List of HTTP methods processed by the server (e.g., ["GET", "POST"]).
* ``allowed_versions``: List of supported HTTP protocol versions (e.g., ["HTTP/1.0", "HTTP/1.1"]).

Section: [logging]
------------------

* ``log_level``: Severity filter level (INFO, WARN, ERROR).
* ``file_logging_enabled``: Whether to enable logging to a specific file on disk.
"""


def render_testing_page() -> str:
    return """
Testing
=======

.. This file is auto-generated by scripts/generate_api_rst.py.

The ``HTTPServer`` project maintains a rigorous testing strategy combining unit tests for core logic and integration tests for end-to-end behavior.

Testing Infrastructure
----------------------

The project uses two primary testing frameworks:

1. **GoogleTest**: For C++ unit testing of library components.
2. **Pytest**: For high-level integration testing of the server binary and its network behavior.

Unit Tests
----------

Unit tests are located in ``tests/unit_tests/`` and focus on individual components in isolation.

Key test suites include:

* ``test_httpparser.cpp``: Comprehensive testing of HTTP request parsing, including edge cases and malformed requests.
* ``test_router.cpp``: Validates routing logic, static directory serving, and dynamic path matching.

To run unit tests:

.. code-block:: bash

   make unit_test

Integration Tests
-----------------

Integration tests are located in ``tests/integration_tests/`` and utilize Python's ``pytest`` framework. These tests spin up the actual server binary and perform real network requests over the loopback interface.

Key coverage areas include:

* **Basic Functionality**: Verifying GET/POST requests and response codes.
* **Server Lifecycle**: Testing startup, shutdown, and signal handling.
* **Network Features**: Validating HTTPS/TLS, port redirection, and keep-alive connections.
* **Performance & Safety**: Testing rate limiting, thread pool behavior, and concurrent connection management.
* **Error Handling**: Ensuring the server correctly handles internal errors and invalid client behavior.

To run integration tests:

.. code-block:: bash

   make integration_test

Running All Tests
-----------------

To run the entire test suite (unit and integration):

.. code-block:: bash

   make test
"""


def render_conf_py(project: str) -> str:
    return f"""
project = "{project}"
author = "{project} contributors"

extensions = [
    "breathe",
    "myst_parser",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

html_theme = "furo"
html_static_path = ["_static"]
suppress_warnings = ["duplicate_declaration.cpp"]

breathe_projects = {{
    "{project}": "_build/doxygen/xml",
}}
breathe_default_project = "{project}"
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--index-xml", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--project", default="HTTPServer")
    args = parser.parse_args()

    headers = parse_header_files(args.index_xml)

    api_dir = args.output.parent / "api"
    if api_dir.exists():
        shutil.rmtree(api_dir)
    api_dir.mkdir(parents=True, exist_ok=True)

    for header in headers:
        (api_dir / f"{page_slug(header)}.rst").write_text(
            render_header_page(header, args.project),
            encoding="utf-8",
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_api_index(headers), encoding="utf-8")

    index_page = args.output.parent / "index.rst"
    index_page.write_text(render_index_page(), encoding="utf-8")

    installation_rst = args.output.parent / "installation.rst"
    installation_rst.write_text(render_installation_page(), encoding="utf-8")

    testing_rst = args.output.parent / "testing.rst"
    testing_rst.write_text(render_testing_page(), encoding="utf-8")

    architecture_rst = args.output.parent / "architecture.rst"
    architecture_rst.write_text(render_architecture_page(), encoding="utf-8")

    metrics_rst = args.output.parent / "metrics.rst"
    metrics_rst.write_text(render_metrics_page(), encoding="utf-8")

    usage_rst = args.output.parent / "usage.rst"
    usage_rst.write_text(render_usage_page(), encoding="utf-8")

    config_rst = args.output.parent / "configuration.rst"
    config_rst.write_text(render_config_page(), encoding="utf-8")

    conf_py = args.output.parent / "conf.py"
    conf_py.write_text(render_conf_py(args.project), encoding="utf-8")

    (args.output.parent / "_static").mkdir(exist_ok=True)
    (args.output.parent / "_templates").mkdir(exist_ok=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
