name: Format

on:
  pull_request:
    branches: [ main ]
  push :
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting (lib only)
        run: |
            FILES=$(find lib -type f \( -name "*.cpp" -o -name "*.h" \))
            if [ -n "$FILES" ]; then
            clang-format --dry-run --Werror $FILES
            fi